# Generated by Django 6.0 on 2025-12-12 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "planned_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SA", "Savings"),
                            ("EX", "Expenses"),
                            ("AC", "Accumulative"),
                        ],
                        default="SA",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PL", "Planned"),
                            ("CP", "Completed"),
                            ("OG", "Ongoing"),
                            ("CL", "Cancelled"),
                        ],
                        default="PL",
                        max_length=2,
                    ),
                ),
                (
                    "accessibility",
                    models.CharField(
                        choices=[
                            ("PRI", "Private"),
                            ("PUB", "Public"),
                            ("GRP", "Group"),
                        ],
                        default="PRI",
                        max_length=3,
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events_table",
            },
        ),
        migrations.CreateModel(
            name="EventMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AD", "Admin"),
                            ("MOD", "Moderator"),
                            ("MEM", "Member"),
                        ],
                        default="MEM",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("BN", "Banned"),
                            ("DI", "Disabled"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                ("join_date", models.DateField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events_membership",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="unique_event_user"
                    )
                ],
            },
        ),
    ]
