# Generated by Django 6.0 on 2025-12-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="planned_budget",
            new_name="planned_amount",
        ),
    ]
