# Generated by Django 6.0 on 2025-12-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_planned_budget_event_planned_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="accessibility",
            field=models.CharField(
                choices=[
                    ("Private", "Private"),
                    ("Public", "Public"),
                    ("Group", "Group"),
                ],
                default="Private",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planned", "Planned"),
                    ("Completed", "Completed"),
                    ("Ongoing", "Ongoing"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Planned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("Savings", "Savings"),
                    ("Expenses", "Expenses"),
                    ("Accumulative", "Accumulative"),
                ],
                default="Savings",
                max_length=20,
            ),
        ),
    ]
