# Generated by Django 6.0 on 2025-12-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_accessibility_alter_event_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Moderator", "Moderator"),
                    ("Member", "Member"),
                    ("Creator", "Creator"),
                ],
                default="Member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Banned", "Banned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="event",
            table="events",
        ),
    ]
