# Generated by Django 6.0 on 2025-12-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_eventmembership_role_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="type",
            new_name="even_type",
        ),
    ]
