# Generated by Django 6.0 on 2025-12-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_rename_type_event_even_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="even_type",
            new_name="event_type",
        ),
    ]
