# Generated by Django 6.0 on 2025-12-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userconnection"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_usernam_baeb4b_idx",
            old_name="user_usernam_b79065_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_email_4b85f2_idx",
            old_name="user_email_7bbb4c_idx",
        ),
        migrations.AlterField(
            model_name="userconnection",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Accepted", "Accepted")],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
