# Generated by Django 6.0 on 2025-12-18 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_rename_user_usernam_b79065_idx_users_usernam_baeb4b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="connect_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
