# Generated by Django 6.0 on 2025-12-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_unique_email_for_each_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userconnection",
            options={"ordering": ["status"]},
        ),
    ]
