# Generated by Django 6.0 on 2025-12-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userconnection_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("USD", "Usd"),
                    ("EUR", "Eur"),
                    ("JPY", "Jpy"),
                    ("CHF", "Chf"),
                    ("DKK", "Dkk"),
                    ("UAH", "Uah"),
                    ("GBP", "Gbp"),
                    ("AUD", "Aud"),
                    ("CAD", "Cad"),
                    ("CNY", "Cny"),
                    ("HKD", "Hkd"),
                    ("NZD", "Nzd"),
                    ("SEK", "Sek"),
                    ("NOK", "Nok"),
                    ("INR", "Inr"),
                    ("SGD", "Sgd"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="job",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
