# Generated by Django 6.0 on 2025-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="state",
            field=models.CharField(
                choices=[("Permanent", "Permanent"), ("Temporary", "Temporary")],
                default="Permanent",
                max_length=20,
            ),
        ),
    ]
