# Generated by Django 6.0 on 2025-12-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_eventmembership_role_and_more"),
        ("groups", "0002_alter_group_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupeventconnection",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_link",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="groupeventconnection",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_link",
                to="groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Moderator", "Moderator"),
                    ("Member", "Member"),
                    ("Creator", "Creator"),
                ],
                default="Member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Banned", "Banned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="group",
            table="a_groups",
        ),
    ]
