# Generated by Django 6.0 on 2025-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")],
                default="Income",
                max_length=20,
            ),
        ),
    ]
