# Generated by Django 6.0 on 2025-12-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="budget",
            table="budgets",
        ),
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="services",
        ),
    ]
