# Generated by Django 6.0 on 2025-12-21 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_alter_budget_table_alter_category_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
