# Generated by Django 6.0 on 2025-12-22 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_alter_category_type_alter_transaction_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="type",
            new_name="category_type",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="type",
            new_name="transaction_type",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finances.category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="finances.budget",
            ),
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="transactions",
        ),
    ]
